application: kleinegutenberg
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: pub/index.html
  upload: pub/index.html
  secure: always
- url: /s/
  static_dir: pub
  application_readable: true
  secure: always
- url: /.*
  script: _go_app
